apiVersion: apps/v1
kind: Deployment
metadata:
  name: sirekap-backend-deployment
  labels:
    app: sirekap-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sirekap-backend
  template:
    metadata:
      labels:
        app: sirekap-backend
    spec:
      containers:
        - name: sirekap-backend
          image: nathanielj108/sirekap-backend:latest
          ports:
            - containerPort: 8080
