apiVersion: v1
kind: Service
metadata:
  name: sirekap-backend-service
spec:
  selector:
    app: sirekap-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
